trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: FirstJob
        steps:
          - bash: echo Build FirstJob
      - job: SecondJob
        steps:
          - bash: echo Build SecondJob

  - stage: DevDeployuild
    jobs:
      - job: DevDployJob
        steps:
          - bash: echo DevDeployJob

  - stage: QADeploy
    jobs:
      - job: QADeployJob
        steps:
          - bash: echo QADeployJob

  - stage: ProdDeployJob
    jobs:
      - job: ProdDeployJob
        steps:
          - bash: echo ProdDeployJob

  # - stage: DevDeploy
  #     - job: DevDeployJob
  #       steps:
  #         - bash: echo DevDeployJob

  # - stage: QADeploy
  #     - job: QADeployJob
  #       steps:
  #         - bash: echo QADeployJob

  # - stage: ProdDeploy
  #      - job: ProdDeployJob
  #        steps:
  #         - bash: echo ProdDeployJob